[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Oh-My-Wrist"
version = "0.1.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    # Add your external dependencies here, for example:
    # "requests>=2.28.0",
]
